### ISSUE TITLE
To-do for Week 12

### ISSUE THREAD

**Issue by Mitarashiharuto** [CenterForTheBuiltEnvironment/comfort-dash#79]
- [x] make the chart grid faded
- [x] check calculation of air speed
- [x] change comfort range code in pr 73 - more flexible
- [ ] compare function data - refer to input 1 and 2
- [x] change the dot color
- [ ] do pr 72 and 73 first - before Monday, then check 78 before Thursday
